# Generated by Django 4.0.1 on 2022-02-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='estimatedTimeOfDeparture',
            field=models.TimeField(),
        ),
    ]
